#!/bin/bash
app=jappix

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

# Source YNH helpers
. /usr/share/yunohost/helpers

app=${!#}

# Retrieve app settings
domain=$(sudo yunohost app setting "$app" domain)

# Save sources & data
ynh_backup "/var/www/${app}" "sources"

# Copy NGINX configuration
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"
