#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -eu

# Source YNH helpers
source /usr/share/yunohost/helpers

app="jappix"

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)

# Save sources & data
ynh_backup "/var/www/${app}" "sources"

# Copy NGINX configuration
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"
