#!/bin/bash

app=${!#}

# Retrieve arguments
backup_dir=$1

# Retrieve app settings
domain=$(sudo yunohost app setting "$app" domain)

# Save sources & data
sudo cp -a "/var/www/${app}" ./sources

# Copy NGINX configuration
sudo cp -a "/etc/nginx/conf.d/${domain}.d/${app}.conf" ./nginx.conf
