#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE FAILURE OF THE SCRIPT
#=================================================

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
name=$YNH_APP_ARG_NAME
language=$YNH_APP_ARG_LANGUAGE

app=$YNH_APP_INSTANCE_NAME

#=================================================
# Check domain/path availability
#=================================================

CHECK_PATH	# Vérifie et corrige la syntaxe du path.
CHECK_DOMAINPATH
CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set $app name $name
ynh_app_setting_set $app language $language
ynh_app_setting_set $app domain $domain
ynh_app_setting_set $app final_path $final_path

#=================================================
# Copy files to the right place
#=================================================

SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path

mkdir -p "${final_path}/store/conf"
cp ../conf/*.xml "${final_path}/store/conf/"

#=================================================
# Set permissions to jappix directory
#=================================================

chown -R www-data: "$final_path"

#=================================================
# Set and copy NGINX configuraion
#=================================================

sed -i "s@PATHTOCHANGE@${path}@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@${final_path}/@g" ../conf/nginx.conf
cp ../conf/nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

#=================================================
# Validate language
#=================================================

[[ -e "${final_path}/i18n/${language}" ]] \
  || language="en"

#=================================================
# Set Jappix configuration
#=================================================

sed -i "s@PATHTOCHANGE@${path}@g" "${final_path}/store/conf/hosts.xml"
sed -i "s@CHANGELANG@${language}@g" "${final_path}/store/conf/main.xml"
sed -i "s@CHANGENAME@${name}@g" "${final_path}/store/conf/main.xml"
sed -i "s@DOMAINTOCHANGE@${domain}@g" "${final_path}/store/conf/hosts.xml"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading nginx web server..." -weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last

