#!/bin/bash

set -e

source ./_common.sh

app=${!#}

# Retrieve arguments
domain=$1
path=${2%/}
name=$3
language=$4

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
  || exit 1

# Retrieve sources
wget -q -O jappix.tar.gz "$JAPPIX_SOURCE_URL"

# Copy files to the right place
final_path="/var/www/${app}"
sudo mkdir -p "${final_path}/store/conf"
sudo tar -C "$final_path" -xf jappix.tar.gz --strip-components 1
sudo cp ../conf/*.xml "${final_path}/store/conf/"

# Set permissions to jappix directory
sudo chown -R www-data: "$final_path"

# Set and copy NGINX configuraion
sudo sed -i "s@PATHTOCHANGE2@${path}@g" ../conf/nginx.conf
path=${path:-/}
sudo sed -i "s@PATHTOCHANGE@${path}@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@${final_path}/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Validate language
[[ -a "${final_path}/i18n/${language}" ]] \
  || language="en"

# Store app settings
sudo yunohost app setting "$app" name -v "$name"
sudo yunohost app setting "$app" language -v "$language"

# Set Jappix configuration
sudo sed -i "s@PATHTOCHANGE@${path}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@PATHTOCHANGE@${path}@g" "${final_path}/store/conf/hosts.xml"
sudo sed -i "s@DOMAINTOCHANGE@${domain}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@CHANGELANG@${language}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@CHANGENAME@${name}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@DOMAINTOCHANGE@${domain}@g" "${final_path}/store/conf/hosts.xml"

# Reload services
sudo service nginx reload
