#!/bin/bash

set -u
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_get "$app" domain)

# Remove sources and configuration
ynh_secure_remove --file="/var/www/${app}"
ynh_secure_remove --file="/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
sudo service nginx reload
