#!/bin/bash

set -u
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$(ynh_app_setting_set "$app" domain)

# Remove sources and configuration
sudo rm -rf "/var/www/${app}"
sudo rm -f "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
sudo service nginx reload
