#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get "$app" domain)

#=================================================
# REMOVE APP MAIN DIR
#=================================================

# Remove sources and configuration
ynh_secure_remove --file="/var/www/$app"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================

ynh_secure_remove --file="/etc/nginx/conf.d/$domain.d/$app.conf"


# Reload services
ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
