#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

#Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

# Retrieve old app settings
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

# Restore sources & data
cp -a ./sources "/var/www/${app}"

# Restore Nginx and YunoHost parameters
cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
service nginx reload
