#!/bin/bash

# causes the shell to exit if any subcommand or pipeline returns a non-zero status
set -e

app="jappix"

# Retrieve old app settings
domain=$(sudo yunohost app setting "$app" domain)

# Restore sources & data
sudo cp -a ./sources "/var/www/${app}"

# Restore Nginx and YunoHost parameters
sudo cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Reload services
sudo service nginx reload
