#!/bin/bash

source ./_common.sh

app=${!#}

# Retrieve arguments
domain=$(sudo yunohost app setting "$app" domain)
path=$(sudo yunohost app setting "$app" path)
name=$(sudo yunohost app setting "$app" name)
language=$(sudo yunohost app setting "$app" language)

if [[ "$name" = "" ]];
then
    name="YunoJappix"
fi
if [[ "$language" = "" ]];
then
    language="en"
fi

# Remove trailing "/" for next commands
path=${path%/}

# Retrieve sources
wget -nv -O jappix.tar.gz https://github.com/jappix/jappix/archive/${VERSION}.tar.gz

# Copy files to the right place
final_path="/var/www/${app}"
sudo mkdir -p "$final_path"
sudo tar -C "$final_path" -xf jappix.tar.gz --strip-components 1
sudo cp ../conf/*.xml "${final_path}/store/conf/"

# Set permissions to jappix directory
sudo chown -R www-data: "$final_path"

# Modify Nginx configuration file and copy it to Nginx conf directory
sudo sed -i "s@PATHTOCHANGE2@${path}@g" ../conf/nginx.conf

if [ -z "$path" ]; then
  path="/"
fi

sudo sed -i "s@PATHTOCHANGE@${path}@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@${final_path}/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"
sudo sed -i "s@PATHTOCHANGE@${path}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@PATHTOCHANGE@${path}@g" "${final_path}/store/conf/hosts.xml"
sudo sed -i "s@DOMAINTOCHANGE@${domain}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@CHANGELANG@${language}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@CHANGENAME@${name}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@DOMAINTOCHANGE@${domain}@g" "${final_path}/store/conf/hosts.xml"

# Reload services
sudo service nginx reload
