#!/bin/bash

set -eu
source .fonctions
source /usr/share/yunohost/helpers

app="jappix"

# Récupère les infos de l'application.
domain=$(ynh_app_setting_get $app domain)
path=$(ynh_app_setting_get $app path)
name=$(ynh_app_setting_get "$app" name)
language=$(ynh_app_setting_get "$app" language)

# Set default values
name="${name:-YunoJappix}"
language="${language:-en}"

# Remove trailing "/" for next commands
CHECK_PATH

#=================================================
# Copy files to the right place
#=================================================

final_path="/var/www/${app}"
ynh_app_setting_set $app final_path $final_path
SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
sudo mkdir -p "${final_path}/store/conf"
sudo cp ../conf/*.xml "${final_path}/store/conf/"

# Set permissions to jappix directory
sudo chown -R www-data: "$final_path"

# Set and copy NGINX configuraion
sudo sed -i "s@PATHTOCHANGE2@${path}@g" ../conf/nginx.conf
path=${path:-/}
sudo sed -i "s@PATHTOCHANGE@${path}@g" ../conf/nginx.conf
sudo sed -i "s@ALIASTOCHANGE@${final_path}/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Set Jappix configuration
sudo sed -i "s@PATHTOCHANGE@${path}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@PATHTOCHANGE@${path}@g" "${final_path}/store/conf/hosts.xml"
sudo sed -i "s@DOMAINTOCHANGE@${domain}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@CHANGELANG@${language}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@CHANGENAME@${name}@g" "${final_path}/store/conf/main.xml"
sudo sed -i "s@DOMAINTOCHANGE@${domain}@g" "${final_path}/store/conf/hosts.xml"

# Reload services
sudo service nginx reload
